# Generated by Django 5.0.1 on 2024-02-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('image', models.ImageField(default='null.jpg', upload_to='image')),
                ('category', models.TextField(max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
