# Generated by Django 5.0.1 on 2024-03-06 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_product_description_alter_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='Category',
        ),
    ]
