# Generated by Django 5.0.1 on 2024-03-06 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_rename_category_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
